name: Run linter and tests

on:
  push:
    branches-ignore:
      - master

jobs:
  linter-and-tests:
    name: Linter and tests

    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup Nodejs and npm
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2
          cache: npm

      - name: Install dependencies
        run: npm install

      - name: Generate types
        run: npm run prepare

      - name: Run linter
        run: npm run lint

      - name: Run unit tests
        run: npm run test:coverage
